# j2objc is a mixed-language project, but setting objective-c forces the OS to OSX.
language: objective-c
os: osx
osx_image: xcode8.2
sudo: false

env:
  - LATEST_JAVA=true

matrix:
  allow_failures:
    - env: LATEST_JAVA=true

before_script:
  - scripts/osx-set-java.sh

# Travis-CI kills the build after 50 minutes, so break it up into
# smaller commands and only build one arch.
script: J2OBJC_ARCHS="iphone" make -j4 dist
after_script:
  - make test_translator
  - make test_cycle_finder
  - make test_jre_cycles
  - make test_guava_cycles
